version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        identifier: gz_raw_product
      - name: sales
        identifier: gz_raw_sales
      - name: ship
        identifier: gz_raw_ship


